ALTER TABLE petalops.empresa
  ALTER COLUMN nit DROP NOT NULL,
  ALTER COLUMN nit TYPE VARCHAR(40),
  ADD COLUMN IF NOT EXISTS ciudad VARCHAR(120),
  ADD COLUMN IF NOT EXISTS direccion VARCHAR(180),
  ADD COLUMN IF NOT EXISTS nombre_responsable VARCHAR(180),
  ADD COLUMN IF NOT EXISTS cargo_responsable VARCHAR(120),
  ADD COLUMN IF NOT EXISTS correo_responsable VARCHAR(180),
  ADD COLUMN IF NOT EXISTS celular_responsable VARCHAR(40);

