ALTER TABLE Entrega
  ADD COLUMN IF NOT EXISTS tipoEntrega VARCHAR(30) NULL AFTER estadoEntregaID,
  ADD COLUMN IF NOT EXISTS destinatario VARCHAR(200) NULL AFTER tipoEntrega,
  ADD COLUMN IF NOT EXISTS telefonoDestino VARCHAR(30) NULL AFTER destinatario,
  ADD COLUMN IF NOT EXISTS direccion VARCHAR(250) NULL AFTER telefonoDestino,
  ADD COLUMN IF NOT EXISTS barrioID BIGINT NULL AFTER direccion,
  ADD COLUMN IF NOT EXISTS barrioNombre VARCHAR(150) NULL AFTER barrioID,
  ADD COLUMN IF NOT EXISTS rangoHora VARCHAR(100) NULL AFTER fechaEntrega,
  ADD COLUMN IF NOT EXISTS mensaje TEXT NULL AFTER rangoHora,
  ADD COLUMN IF NOT EXISTS firma VARCHAR(150) NULL AFTER mensaje,
  ADD COLUMN IF NOT EXISTS observacionGeneral TEXT NULL AFTER firma;
