SELECT 
    c.TABLE_NAME AS Tabla,
    c.COLUMN_NAME AS Columna,
    c.COLUMN_TYPE AS Tipo,
    c.IS_NULLABLE AS Permite_Null,
    c.COLUMN_KEY AS Tipo_Clave,
    c.COLUMN_DEFAULT AS Valor_Por_Defecto,
    c.EXTRA AS Extra,
    k.REFERENCED_TABLE_NAME AS Tabla_Referenciada,
    k.REFERENCED_COLUMN_NAME AS Columna_Referenciada
FROM INFORMATION_SCHEMA.COLUMNS c
LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE k
    ON c.TABLE_SCHEMA = k.TABLE_SCHEMA
    AND c.TABLE_NAME = k.TABLE_NAME
    AND c.COLUMN_NAME = k.COLUMN_NAME
WHERE c.TABLE_SCHEMA = 'joindata_app'
ORDER BY c.TABLE_NAME, c.ORDINAL_POSITION;